### ISSUE TITLE
when input element  focus or touched ,the element no class ng-touched 

### ISSUE THREAD

**Issue by wqdjl** [NepipenkoIgor/ngx-mask#25]
class="form-control ng-valid ng-untouched ng-dirty"

after focus or touched should class="form-control ng-valid ng-touched ng-dirty"

**Comment by victorschinaider** [comment]
It was implemented, i will make a pull request soon. Thanks.

**Comment by LimarenkoDenis** [comment]
@wqdjl It works fine right now, please update version and check
