### ISSUE TITLE
Problem resetting the value of masked input field

### ISSUE THREAD

**Issue by xorost** [NepipenkoIgor/ngx-mask#31]
Passing null, undefined or empty string as the value for masked input does not reset its value as expected; masked input just does not change at all. Most likely it happens because of the check in [mask.directive.ts](https://github.com/NepipenkoIgor/ngx-mask/blob/master/src/app/ngx-mask/mask.directive.ts) method writeValue:
```
public writeValue(inputValue: string): void {
    if (!inputValue) {
      return; }
```
The only thing that works is setting input value to a string containing just a single space symbol, though setting null or undefined seems like expected behaviour.

**Comment by jdgarvey** [comment]
@xorost 
just had this problem and your space hack worked, thank you. 

@NepipenkoIgor 
Wondering if there really needs to be an "empty" check in `writeValue`?

**Comment by revshri** [comment]
Even after making the ngModel or formcontrolname value to null or empty string with "", the input control seems to clear but when you start typing the previous value of hiddeninput is retained and the first digit of the value is not overridden. How to reset the value to prevent the retaining of hiddenvalue's previous value?
