### ISSUE TITLE
Is it possible to enter non-english characters with A/S mask?

### ISSUE THREAD

**Issue by sharikovvladislav** [NepipenkoIgor/ngx-mask#37]
For example Russian letters :)

**Comment by NepipenkoIgor** [comment]
@sharikovvladislav  yes , use configuration, 
for example in module

```
    NgxMaskModule.forRoot({
      clearIfNotMatch: true,
      dropSpecialCharacters: true,
      specialCharacters: ['(', ')'],
      patterns:
        {
          '0':
            {
              pattern: new RegExp('\[а-яА-Я\]')
            }
        }
    }),
```
or you could do this inline

**Comment by sharikovvladislav** [comment]
True! Is it possible to add new characters in patterns block? 

So 0 will work as 'out-of-the-box'?

**Comment by NepipenkoIgor** [comment]
@sharikovvladislav  Yes, 
 patterns:
        {
          'L': // some char 
            {
              pattern: new RegExp('\[а-яА-Я\]')
            }
        }

**Comment by sharikovvladislav** [comment]
True. Ty! Ty for your you awesome lib!

**Comment by NepipenkoIgor** [comment]
@sharikovvladislav  Thanks
